# Generated by Django 6.0.1 on 2026-02-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('win_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesmodel',
            name='highlight_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='courses/highlights/'),
        ),
        migrations.AddField(
            model_name='coursesmodel',
            name='highlight_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='courses/highlights/'),
        ),
        migrations.AddField(
            model_name='coursesmodel',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/main/'),
        ),
    ]
