# Generated by Django 6.0.1 on 2026-02-21 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('win_app', '0004_sitepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Course Syllabus', max_length=200)),
                ('content', models.TextField(help_text='Add full syllabus content here')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='courses/syllabus/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='win_app.coursesmodel')),
            ],
            options={
                'verbose_name_plural': 'COURSE SYLLABUS',
                'db_table': 't_course_syllabus',
            },
        ),
    ]
