# Generated by Django 6.0.1 on 2026-02-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('win_app', '0006_alter_event_date_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='faculty_category',
            field=models.CharField(blank=True, choices=[('bsc', 'BSc / PBSc'), ('gnm', 'GNM')], max_length=20, null=True),
        ),
    ]
