# Generated by Django 5.2.8 on 2026-03-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('win_app', '0007_administration_faculty_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='mother_name',
        ),
        migrations.AddField(
            model_name='administration',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='father_first_name',
            field=models.CharField(default='Not Updated', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='father_last_name',
            field=models.CharField(default='Not Updated', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='mother_first_name',
            field=models.CharField(default='Not Updated', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='mother_last_name',
            field=models.CharField(default='Not Updated', max_length=100),
            preserve_default=False,
        ),
    ]
