# Generated by Django 6.0.1 on 2026-03-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('win_app', '0008_remove_application_father_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesmodel',
            name='course_fees',
        ),
    ]
