# Generated by Django 6.0.1 on 2026-03-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('win_app', '0011_contactmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesmodel',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
