# Generated by Django 6.0.1 on 2026-03-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('win_app', '0014_alter_application_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Others')], max_length=10, null=True),
        ),
    ]
