# Generated by Django 6.0.1 on 2026-03-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('win_app', '0015_alter_application_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
