# Generated by Django 6.0.1 on 2026-03-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('win_app', '0016_application_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization/'),
        ),
    ]
