# Generated by Django 6.0.1 on 2026-03-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('win_app', '0018_popupmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PopupMessage',
        ),
    ]
